// Shield decoration configuration. Keep mask order here; assets live in masks/1x.
window.MASK_CONFIG = {
  path: 'masks/1x',
  baseSize: 128,
  sizeOptions: [
    { scale: 2, pixels: 192 },
    { scale: 1.5, pixels: 160 },
    { scale: 1, pixels: 128 }
  ],
  moveStep: 4,
  masks: [
    ['Ancient Bordure', 'm_Anc_Bordure.png'],
    ['Bar Pale', 'm_Bar_Pale.png'],
    ['Bar', 'm_Bar.png'],
    ['Bars', 'm_Bars.png'],
    ['Base', 'm_Base.png'],
    ['Bend', 'm_Bend.png'],
    ['Bendlets', 'm_Bendlets.png'],
    ['Bendy', 'm_Bendy.png'],
    ['Checky', 'm_Checky.png'],
    ['Chevron Pale', 'm_Chevron_Pale.png'],
    ['Chevron Sinister', 'm_Chevron_Sinister.png'],
    ['Chevronel', 'm_Chevronel.png'],
    ['Chief Pale', 'm_Chief_Pale.png'],
    ['Chief Pale (legacy)', 'ь_Chief_Pale.png'],
    ['Chief', 'm_Chief.png'],
    ['Cross', 'm_Cross.png'],
    ['Fess', 'm_Fess.png'],
    ['Flangel', 'm_Flangel.png'],
    ['Gyronny', 'm_Gyronny.png'],
    ['Lozenge', 'm_Lozenge.png'],
    ['Man', 'm_Man.png'],
    ['Pagan Bordure', 'm_Pag_Bordure.png'],
    ['Pale', 'm_Pale.png'],
    ['Pall', 'm_Pall.png'],
    ['Pallet', 'm_Pallet.png'],
    ['Pallets', 'm_Pallets.png'],
    ['Per Bend', 'm_per_Bend.png'],
    ['Per Chevron', 'm_per_Chevron.png'],
    ['Per Fess', 'm_per_Fess.png'],
    ['Per Pale', 'm_per_Pale.png'],
    ['Per Pile', 'm_per_Pile.png'],
    ['Per Saltire', 'm_per_Saltire.png'],
    ['Quarter', 'm_Quarter.png'],
    ['Quarterly', 'm_Quarterly.png'],
    ['Remnant Bordure', 'm_Rem_Bordure.png'],
    ['Saltire', 'm_Saltire.png']
  ].map(([name, file]) => ({ name, file }))
};
